name: CI

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        sleep 5
    
    - name: Run tests
      run: |
        echo "Running tests..."
        sleep 10
        echo "✅ All tests passed!"
    
    - name: Build
      run: |
        echo "Building application..."
        sleep 5
        echo "✅ Build successful!"