name: Lint

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Run ESLint
      run: |
        echo "Running ESLint..."
        sleep 8
        if [ -f "FAIL_LINT" ]; then
          echo "❌ Linting errors found!"
          exit 1
        fi
        echo "✅ No linting errors found!"
    
    - name: Check formatting
      run: |
        echo "Checking code formatting..."
        sleep 3
        echo "✅ Code is properly formatted!"