name: Lint

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Run ESLint
      run: |
        echo "Running ESLint..."
        sleep 8
        # echo "❌ Simulating linting errors for testing!"
        # exit 1
    
    - name: Check formatting
      run: |
        echo "Checking code formatting..."
        sleep 3
        echo "✅ Code is properly formatted!"